name: 3D Contributions

on:
  schedule:
    - cron: "0 1 * * *"   # 1x par jour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # <— requis
          USERNAME: AhmedAmineBejaoui                 # <— ton username
          OUTPUT_PATH: ./profile-3d-contrib           # dossier de sortie
          SETTINGS: "-l 10 --yearly"                  # options (facultatif)

      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add -A
          git commit -m "chore: update 3d contributions" || echo "no changes"
          git push
