name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # 1x par jour à minuit UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AhmedAmineBejaoui
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Tunis
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_stars: yes
